export const CLINIC = {
  name: "Hollyhill Dental",
  tagline: "Creating Beautiful & Confident Smiles",
  taglineShort: "Smile Confidently",
  address: "Unit 6 Hollyhill Shopping Centre, Co. Cork, T23 E030, Ireland",
  phone: "+353 21 430 3072",
  phoneHref: "tel:+353214303072",
  whatsapp: "https://wa.me/353214303072",
  email: "info@hollyhilldental.ie",
  gdprEmail: "gdpr@hollyhilldental.ie",
  instagram: "@dr.roghay_smile",
  doctor: "Dr. Roghay Alizadeh",
  doctorTitle: "Principal Cosmetic Dentist",
  experience: "20+",
  hours: {
    weekdays: "Mon–Fri: 9:00am–5:30pm",
    saturday: "Sat: 9:00am–2:00pm",
    sunday: "Sun: Closed",
  },
};

export interface ServiceType {
  slug: string;
  name: string;
  category: "general" | "cosmetic" | "orthodontics" | "advanced";
  priceFrom: number;
  priceTo: number;
  duration: number;
  description: string;
}

export const SERVICES: ServiceType[] = [
  {
    slug: "general-dentistry",
    name: "General Dentistry",
    category: "general",
    priceFrom: 50,
    priceTo: 300,
    duration: 30,
    description: "Comprehensive care for your natural smile, including dental fillings, cleanings, and simple extractions.",
  },
  {
    slug: "dental-checkups",
    name: "Dental Check-ups & Examinations",
    category: "general",
    priceFrom: 50,
    priceTo: 80,
    duration: 30,
    description: "Thorough exams, oral cancer screenings, and diagnostic X-rays to safeguard your dental wellness.",
  },
  {
    slug: "teeth-cleaning",
    name: "Hygiene & Teeth Cleaning",
    category: "general",
    priceFrom: 70,
    priceTo: 120,
    duration: 45,
    description: "Professional scaling and polishing to remove plaque, prevent gum disease, and clean stains.",
  },
  {
    slug: "teeth-whitening",
    name: "Teeth Whitening",
    category: "cosmetic",
    priceFrom: 250,
    priceTo: 400,
    duration: 60,
    description: "Safe, medical-grade brightening systems for a radiant smile up to 8 shades lighter.",
  },
  {
    slug: "invisalign",
    name: "Invisalign Clear Aligners",
    category: "orthodontics",
    priceFrom: 2500,
    priceTo: 5000,
    duration: 60,
    description: "Discreet and comfortable clear aligners that straighten crooked teeth without metal brackets.",
  },
  {
    slug: "composite-bonding",
    name: "Composite Bonding",
    category: "cosmetic",
    priceFrom: 250,
    priceTo: 400,
    duration: 60,
    description: "Artistic application of tooth-colored composite resin to restore chipped, cracked, or uneven teeth.",
  },
  {
    slug: "veneers",
    name: "Porcelain Veneers",
    category: "cosmetic",
    priceFrom: 800,
    priceTo: 1200,
    duration: 90,
    description: "Custom-made wafer-thin porcelain shells that cover the front surface of teeth for a flawless smile.",
  },
  {
    slug: "smile-design",
    name: "Smile Design",
    category: "cosmetic",
    priceFrom: 500,
    priceTo: 2000,
    duration: 60,
    description: "Personalized digital analysis to design a balanced smile matching your facial architecture.",
  },
  {
    slug: "root-canal",
    name: "Root Canal Treatment",
    category: "general",
    priceFrom: 600,
    priceTo: 1000,
    duration: 90,
    description: "Gentle therapy to eliminate infection inside a tooth's root canals and prevent extraction.",
  },
  {
    slug: "dental-crowns",
    name: "Dental Crowns",
    category: "advanced",
    priceFrom: 800,
    priceTo: 1000,
    duration: 90,
    description: "Bespoke tooth-shaped caps that encase cracked, weak, or heavily filled teeth to restore durability.",
  },
  {
    slug: "tooth-extractions",
    name: "Tooth Extractions",
    category: "general",
    priceFrom: 120,
    priceTo: 250,
    duration: 30,
    description: "Safe and comfortable extraction of damaged, decayed, or crowded teeth including wisdom teeth.",
  },
  {
    slug: "emergency-dentistry",
    name: "Emergency Dentistry",
    category: "general",
    priceFrom: 80,
    priceTo: 300,
    duration: 45,
    description: "Urgent care for toothaches, oral trauma, loose restorations, or sudden swelling in Cork.",
  },
  {
    slug: "dental-bridges",
    name: "Dental Bridges",
    category: "advanced",
    priceFrom: 1200,
    priceTo: 2000,
    duration: 90,
    description: "Fixed prostheses that span gaps left by missing teeth, anchored to adjacent healthy teeth.",
  },
  {
    slug: "gum-treatment",
    name: "Gum Treatment",
    category: "advanced",
    priceFrom: 150,
    priceTo: 400,
    duration: 60,
    description: "Periodontal therapies designed to treat gingivitis, deep plaque build-up, and gum recession.",
  },
  {
    slug: "composite-fillings",
    name: "Composite Fillings",
    category: "general",
    priceFrom: 80,
    priceTo: 200,
    duration: 30,
    description: "Natural-looking white fillings placed to restore teeth affected by cavities or minor damage.",
  },
  {
    slug: "dentures",
    name: "Dentures",
    category: "advanced",
    priceFrom: 800,
    priceTo: 2000,
    duration: 60,
    description: "Removable partial or full teeth arches made to look and act like natural dentition.",
  },
  {
    slug: "full-smile-makeovers",
    name: "Full Smile Makeovers",
    category: "cosmetic",
    priceFrom: 3000,
    priceTo: 8000,
    duration: 120,
    description: "A complete overhaul utilizing combinations of whitening, veneers, crowns, and orthodontics.",
  },
  {
    slug: "digital-smile-consultation",
    name: "Digital Smile Consultation",
    category: "cosmetic",
    priceFrom: 0,
    priceTo: 100,
    duration: 45,
    description: "An interactive session mapping your cosmetic goals using high-resolution digital photography.",
  },
];
