export const CLINIC = {
  name: "Hollyhill Dental",
  tagline: "Creating Beautiful & Confident Smiles",
  taglineShort: "Smile Confidently",
  address: "Unit 6 Hollyhill Shopping Centre, Co. Cork, T23 E030, Ireland",
  phone: "+353 21 430 3072",
  phoneHref: "tel:+353214303072",
  whatsapp: "https://wa.me/353830046288",
  whatsappDisplay: "083 004 6288",
  email: "info@hollyhilldental.ie",
  gdprEmail: "gdpr@hollyhilldental.ie",
  instagram: "@dr.roghay_smile",
  doctor: "Dr. Roghay Alizadeh",
  doctorTitle: "Principal Cosmetic Dentist",
  experience: "20+",
  hours: {
    weekdays: "Mon–Fri: 9:00am–5:30pm",
    saturday: "Sat: 9:00am–2:00pm",
    sunday: "Sun: Closed",
  },
};

export interface ServiceType {
  slug: string;
  name: string;
  category: "general" | "cosmetic" | "orthodontics" | "advanced";
  priceFrom: number;
  priceTo: number;
  duration: number;
  description: string;
}

export const SERVICES: ServiceType[] = [
  // GENERAL
  {
    slug: "general-dentistry",
    name: "General Dentistry",
    category: "general",
    priceFrom: 40,
    priceTo: 200,
    duration: 30,
    description: "Comprehensive care for your natural smile, including dental fillings, cleanings, and simple extractions.",
  },
  {
    slug: "dental-checkups",
    name: "First Consultation",
    category: "general",
    priceFrom: 40,
    priceTo: 40,
    duration: 30,
    description: "Thorough exams, oral cancer screenings, and diagnostic checkups to safeguard your dental wellness.",
  },
  {
    slug: "teeth-cleaning",
    name: "Exam, Scale & Polish (Same App)",
    category: "general",
    priceFrom: 60,
    priceTo: 60,
    duration: 45,
    description: "Professional scaling and polishing to remove plaque, prevent gum disease, and clean stains in one appointment.",
  },
  {
    slug: "teeth-whitening",
    name: "Teeth Whitening Home Kit",
    category: "cosmetic",
    priceFrom: 199,
    priceTo: 199,
    duration: 60,
    description: "Safe, medical-grade brightening systems for a radiant smile up to 8 shades lighter.",
  },

  // ORTHODONTICS
  {
    slug: "invisalign",
    name: "Invisalign Go - Single",
    category: "orthodontics",
    priceFrom: 2150,
    priceTo: 2150,
    duration: 60,
    description: "Discreet and comfortable clear aligners for a single arch.",
  },
  {
    slug: "invisalign-go-double",
    name: "Invisalign Go - Double",
    category: "orthodontics",
    priceFrom: 2950,
    priceTo: 2950,
    duration: 60,
    description: "Discreet and comfortable clear aligners for double arches.",
  },
  {
    slug: "invisalign-full",
    name: "Invisalign Full",
    category: "orthodontics",
    priceFrom: 4000,
    priceTo: 4000,
    duration: 60,
    description: "Comprehensive clear aligner orthodontic system for complex teeth alignment.",
  },

  // ROOT CANAL
  {
    slug: "root-canal",
    name: "Root Canal (Incisor)",
    category: "advanced",
    priceFrom: 350,
    priceTo: 350,
    duration: 90,
    description: "Gentle therapy to eliminate infection inside an incisor tooth's root canals and prevent extraction.",
  },
  {
    slug: "root-canal-canine",
    name: "Root Canal (Canine)",
    category: "advanced",
    priceFrom: 350,
    priceTo: 350,
    duration: 90,
    description: "Gentle therapy to eliminate infection inside a canine tooth's root canals and prevent extraction.",
  },
  {
    slug: "root-canal-premolar",
    name: "Root Canal (Pre Molar)",
    category: "advanced",
    priceFrom: 450,
    priceTo: 450,
    duration: 90,
    description: "Gentle therapy to eliminate infection inside a premolar tooth's root canals.",
  },
  {
    slug: "root-canal-molar",
    name: "Root Canal (Molar)",
    category: "advanced",
    priceFrom: 650,
    priceTo: 650,
    duration: 90,
    description: "Gentle therapy to eliminate infection inside a molar tooth's complex root canals.",
  },

  // FIXED PROSTHODONTICS
  {
    slug: "composite-bonding",
    name: "Composite Bonding",
    category: "cosmetic",
    priceFrom: 120,
    priceTo: 180,
    duration: 60,
    description: "Artistic application of tooth-colored composite resin to restore chipped, cracked, or uneven teeth.",
  },
  {
    slug: "composite-veneers",
    name: "Composite Veneers",
    category: "cosmetic",
    priceFrom: 180,
    priceTo: 250,
    duration: 60,
    description: "Handcrafted cosmetic composite layers placed directly on the front surface of teeth.",
  },
  {
    slug: "veneers",
    name: "Porcelain Veneers (per tooth)",
    category: "cosmetic",
    priceFrom: 650,
    priceTo: 650,
    duration: 90,
    description: "Custom-made wafer-thin porcelain shells that cover the front surface of teeth for a flawless smile.",
  },
  {
    slug: "dental-crowns",
    name: "Crown (per tooth)",
    category: "advanced",
    priceFrom: 650,
    priceTo: 650,
    duration: 90,
    description: "Bespoke tooth-shaped caps that encase cracked, weak, or heavily filled teeth to restore durability.",
  },
  {
    slug: "dental-bridges",
    name: "Bridges (per unit)",
    category: "advanced",
    priceFrom: 650,
    priceTo: 2000,
    duration: 90,
    description: "Fixed prostheses that span gaps left by missing teeth, anchored to adjacent healthy teeth.",
  },

  // FILLINGS
  {
    slug: "composite-fillings",
    name: "White Filling",
    category: "general",
    priceFrom: 80,
    priceTo: 120,
    duration: 30,
    description: "Natural-looking white fillings placed to restore teeth affected by cavities or minor damage.",
  },
  {
    slug: "silver-fillings",
    name: "Silver Amalgam Filling",
    category: "general",
    priceFrom: 70,
    priceTo: 100,
    duration: 30,
    description: "Highly durable silver fillings to restore posterior decay.",
  },
  {
    slug: "temporary-fillings",
    name: "Temporary Filling",
    category: "general",
    priceFrom: 60,
    priceTo: 60,
    duration: 30,
    description: "Quick temporary protection for dental cavities between major appointments.",
  },

  // EXTRACTIONS
  {
    slug: "tooth-extractions",
    name: "Routine Extraction",
    category: "general",
    priceFrom: 80,
    priceTo: 109,
    duration: 30,
    description: "Safe and comfortable extraction of damaged, decayed, or crowded teeth.",
  },
  {
    slug: "surgical-extractions",
    name: "Surgical Extraction",
    category: "general",
    priceFrom: 150,
    priceTo: 200,
    duration: 45,
    description: "Complex extraction of impacted wisdom teeth or severely broken tooth roots.",
  },

  // PRESERVED ADDITIONAL SERVICES
  {
    slug: "smile-design",
    name: "Smile Design",
    category: "cosmetic",
    priceFrom: 500,
    priceTo: 2000,
    duration: 60,
    description: "Personalized digital analysis to design a balanced smile matching your facial architecture.",
  },
  {
    slug: "emergency-dentistry",
    name: "Emergency Dentistry",
    category: "general",
    priceFrom: 80,
    priceTo: 300,
    duration: 45,
    description: "Urgent care for toothaches, oral trauma, loose restorations, or sudden swelling in Cork.",
  },
  {
    slug: "gum-treatment",
    name: "Gum Treatment",
    category: "advanced",
    priceFrom: 150,
    priceTo: 400,
    duration: 60,
    description: "Periodontal therapies designed to treat gingivitis, deep plaque build-up, and gum recession.",
  },
  {
    slug: "dentures",
    name: "Dentures",
    category: "advanced",
    priceFrom: 800,
    priceTo: 2000,
    duration: 60,
    description: "Removable partial or full teeth arches made to look and act like natural dentition.",
  },
  {
    slug: "full-smile-makeovers",
    name: "Full Smile Makeovers",
    category: "cosmetic",
    priceFrom: 3000,
    priceTo: 8000,
    duration: 120,
    description: "A complete overhaul utilizing combinations of whitening, veneers, crowns, and orthodontics.",
  },
  {
    slug: "digital-smile-consultation",
    name: "Digital Smile Consultation",
    category: "cosmetic",
    priceFrom: 0,
    priceTo: 100,
    duration: 45,
    description: "An interactive session mapping your cosmetic goals using high-resolution digital photography.",
  },
];